import { Timestamp } from 'firebase/firestore';

export type RuleResolutionMode =
  | 'inherit'
  | 'inherit-plus-explicit'
  | 'explicit-only';

// Flashcard Types
export interface Flashcard {
  id: string;    // Unique ID for each card
  front: string; // The term or question
  back: string;  // The definition or answer
  explanation?: string; // Optional longer explanation
  description?: string; // Optional markdown usage example generated by FLASHCARD_DESC rules
}

export interface FlashcardSet {
  id: string;
  userId: string;
  documentId: string;
  documentIds?: string[];
  documentTitle: string;
  title: string;
  flashcards: Flashcard[];
  directoryId: string;
  createdAt: Timestamp;
  updatedAt: Timestamp;
  appliedRuleIds?: string[];
  appliedDescriptionRuleIds?: string[];
  generationStatus?: GenerationStatus;
  generationError?: string;
  completedAt?: Timestamp;
}

// Flashcard API Types
export interface GenerateFlashcardsRequest {
  documentIds: string[];
  directoryId?: string;
  title?: string;
  additionalPrompt?: string;
  /** @deprecated Auto-resolved from directory hierarchy when omitted */
  ruleIds?: string[];
  descriptionRuleIds?: string[];
  additionalRuleIds?: string[];
  ruleResolutionMode?: RuleResolutionMode;
}

export interface GenerateFlashcardsResponse {
  flashcardSetId: string;
  flashcardSet?: FlashcardSet;
}

export interface UpdateFlashcardSetRequest {
  flashcardSetId: string;
  title?: string;
  flashcards?: Flashcard[];
}

// Slide Deck Types
export interface Slide {
  id: string;
  title: string;
  content: string;
  imageStoragePath?: string;
  imageDownloadToken?: string;
  imageUrl?: string;
  speakerNotes?: string;
}

export interface SlideDeck {
  id: string;
  userId: string;
  documentId: string;
  documentIds?: string[];
  documentTitle: string;
  title: string;
  slides: Slide[];
  directoryId: string;
  createdAt: Timestamp;
  updatedAt: Timestamp;
  appliedRuleIds?: string[];
  generationStatus?: GenerationStatus;
  generationError?: string;
  completedAt?: Timestamp;
}

export interface GenerateSlideDeckRequest {
  documentIds: string[];
  directoryId?: string;
  title?: string;
  additionalPrompt?: string;
  /** @deprecated Auto-resolved from directory hierarchy when omitted */
  ruleIds?: string[];
  additionalRuleIds?: string[];
  ruleResolutionMode?: RuleResolutionMode;
}

export interface GenerateSlideDeckResponse {
  slideDeckId: string;
  slideDeck?: SlideDeck;
}

export interface UpdateSlideDeckRequest {
  slideDeckId: string;
  title?: string;
  slides?: Slide[];
}

export interface QuestionKnowledgeMetadata {
  subjectId?: string;
  subjectName?: string;
  knowledgeDomainId?: string;
  knowledgeDomainName?: string;
  topicTags?: string[];
  sourceDocumentIds?: string[];
}

// Quiz Types (Document-centric architecture)
export interface Quiz {
  id: string;
  documentId: string; // Primary reference to the source document
  documentIds?: string[]; // All source documents (multi-doc quizzes)
  title: string;
  questions: QuizQuestion[];
  createdAt: Date;
  userId?: string;
  directoryId: string;

  // New fields for document-based architecture
  generationAttempt?: number; // Track multiple generations per document
  documentTitle?: string; // Cache for performance

  // Rule tracking for followup generation
  followupRuleIds?: string[]; // Rules to use when generating followup explanations
  appliedRuleIds?: string[]; // Rules applied during initial generation
  generationStatus?: GenerationStatus;
  generationError?: string;
  completedAt?: Date;
}

export interface QuizQuestion {
  question: string;
  options: string[]; // 4 options
  correctAnswer: number; // index of correct option
  explanation: string; // Mandatory explanation for the correct answer
  hint?: string; // Optional hint shown via tooltip on lightbulb icon
  knowledge?: QuestionKnowledgeMetadata;
}

// Sequence Quiz — ordering quiz where items must be arranged in the correct sequence
export interface SequenceQuizQuestion {
  question: string;
  items: string[]; // Items in CORRECT order (shuffled at display time on the client)
  explanation: string;
  hint?: string; // Optional hint shown via tooltip on lightbulb icon
  knowledge?: QuestionKnowledgeMetadata;
}

export interface SequenceQuiz {
  id: string;
  userId: string;
  documentId: string;
  documentIds?: string[];
  documentTitle: string;
  title: string;
  questions: SequenceQuizQuestion[];
  directoryId: string;
  createdAt: Timestamp;
  updatedAt: Timestamp;
  generationAttempt?: number;
  followupRuleIds?: string[];
  appliedRuleIds?: string[];
  generationStatus?: GenerationStatus;
  generationError?: string;
  completedAt?: Timestamp;
}

export interface GenerateSequenceQuizRequest {
  documentIds: string[];
  directoryId?: string;
  sequenceQuizName?: string;
  additionalPrompt?: string;
  ruleIds?: string[];
  followupRuleIds?: string[];
  additionalRuleIds?: string[];
  ruleResolutionMode?: RuleResolutionMode;
}

export interface GenerateSequenceQuizResponse {
  sequenceQuizId: string;
  sequenceQuiz?: SequenceQuiz;
}

export interface GetSequenceQuizResponse {
  sequenceQuiz: SequenceQuiz;
}

export interface GetUserSequenceQuizzesResponse {
  sequenceQuizzes: SequenceQuiz[];
}

// Diagram Quiz — multiple choice where each option is a Mermaid diagram
export interface DiagramQuizQuestion {
  question: string;
  diagrams: string[]; // exactly 4 Mermaid diagram sources
  diagramLabels?: string[];
  correctAnswer: number; // 0–3
  explanation: string;
  hint?: string; // Optional hint shown via tooltip on lightbulb icon
  knowledge?: QuestionKnowledgeMetadata;
}

export interface DiagramQuiz {
  id: string;
  userId: string;
  documentId: string;
  documentIds?: string[];
  documentTitle: string;
  title: string;
  questions: DiagramQuizQuestion[];
  directoryId: string;
  createdAt: Timestamp;
  updatedAt: Timestamp;
  generationAttempt?: number;
  followupRuleIds?: string[];
  appliedRuleIds?: string[];
  generationStatus?: GenerationStatus;
  generationError?: string;
  completedAt?: Timestamp;
}

export interface GenerateDiagramQuizRequest {
  documentIds: string[];
  directoryId?: string;
  diagramQuizName?: string;
  additionalPrompt?: string;
  ruleIds?: string[];
  quizRuleIds?: string[];
  followupRuleIds?: string[];
  additionalRuleIds?: string[];
  ruleResolutionMode?: RuleResolutionMode;
}

export interface GenerateDiagramQuizResponse {
  diagramQuizId: string;
  diagramQuiz?: DiagramQuiz;
}

export interface GetDiagramQuizResponse {
  diagramQuiz: DiagramQuiz;
}

export interface GetUserDiagramQuizzesResponse {
  diagramQuizzes: DiagramQuiz[];
}

// Document Types (New document-centric data model)
export interface Document {
  id: string;
  title: string;
  content: string; // Markdown content stored in Firebase Storage
  sourceType: 'url' | 'upload';
  sourceUrl?: string; // For URL-sourced documents
  fileName?: string; // For uploaded documents
  fileSize: number; // In bytes
  wordCount: number;
  readingTime: number; // In minutes
  createdAt: Date;
  userId?: string;
  storageUrl: string; // Firebase Storage download URL for the markdown file
}

// Document Enums
export enum DocumentSourceType {
  URL = 'url',
  UPLOAD = 'upload',
  GENERATED = 'generated'
}

export enum DocumentStatus {
  ACTIVE = 'active',
  ARCHIVED = 'archived', 
  DELETED = 'deleted'
}

// Generation lifecycle status (orthogonal to DocumentStatus)
export type GenerationStatus = 'pending' | 'completed' | 'failed';

export type GenerationRecordType =
  | 'document'
  | 'quiz'
  | 'flashcardSet'
  | 'slideDeck'
  | 'diagramQuiz'
  | 'sequenceQuiz';

export interface StartGenerationResponse {
  success: boolean;
  id: string;
  recordType: GenerationRecordType;
  directoryId: string;
  generationStatus: 'pending';
}

// Enhanced Document interface
export interface DocumentEnhanced {
  id: string;
  userId: string;
  title: string;
  description: string;
  sourceType: DocumentSourceType;
  sourceUrl?: string;
  wordCount: number;
  status: DocumentStatus;
  storageUrl: string;
  storagePath: string;
  tags: string[];
  directoryId: string;
  createdAt: Date | { toDate(): Date }; // Can be Date or Firestore Timestamp
  updatedAt: Date | { toDate(): Date }; // Can be Date or Firestore Timestamp
  // Generation lifecycle (missing means completed for backward compat)
  generationStatus?: GenerationStatus;
  generationError?: string;
  completedAt?: Date | { toDate(): Date };
}

// Directory Types
export interface Directory {
  id: string;
  userId: string;
  name: string;
  parentId: string | null; // null for root directories
  path: string; // Computed path for breadcrumb navigation (e.g., "/Projects/Web")
  level: number; // Tree depth level (0 for root)
  color?: string; // Optional color for visual organization
  icon?: string; // Optional icon name
  description?: string;
  documentCount: number; // Cached count of documents in this directory
  childCount: number; // Cached count of child directories
  quizCount: number;
  flashcardSetCount: number;
  slideDeckCount: number;
  /** Present for directories created after diagram quizzes; treat missing as 0 */
  diagramQuizCount?: number;
  /** Present for directories created after sequence quizzes; treat missing as 0 */
  sequenceQuizCount?: number;
  ruleIds: string[];
  createdAt: Date | { toDate(): Date };
  updatedAt: Date | { toDate(): Date };
}

// Directory Tree Node for UI rendering
export interface DirectoryTreeNode {
  directory: Directory;
  children: DirectoryTreeNode[];
  isExpanded?: boolean;
  isSelected?: boolean;
}

// Directory API Request Types
export interface CreateDirectoryRequest {
  name: string;
  parentId?: string | null;
  color?: string;
  icon?: string;
  description?: string;
}

export interface UpdateDirectoryRequest {
  name?: string;
  color?: string;
  icon?: string;
  description?: string;
}

export interface MoveDirectoryRequest {
  targetParentId: string | null;
}

export interface MoveDocumentRequest {
  targetDirectoryId: string;
}

// Directory API Response Types
export interface CreateDirectoryResponse {
  directoryId: string;
  directory: Directory;
}

export interface GetDirectoryResponse {
  directory: Directory;
}

export interface GetDirectoryTreeResponse {
  tree: DirectoryTreeNode[];
  totalDirectories: number;
}

export interface GetDirectoryContentsResponse {
  directory: Directory;
  subdirectories: Directory[];
  documents: DocumentEnhanced[];
  totalCount: number;
}

export interface GetDirectoryContentsWithArtifactsResponse extends GetDirectoryContentsResponse {
  quizzes: Quiz[];
  flashcardSets: FlashcardSet[];
  slideDecks: SlideDeck[];
  diagramQuizzes: DiagramQuiz[];
  sequenceQuizzes: SequenceQuiz[];
  resolvedRules: {
    rules: Rule[];
    inheritanceMap: { [directoryId: string]: Rule[] };
  };
}

export type ArtifactSummaryType = 'quiz' | 'flashcard' | 'slideDeck' | 'diagramQuiz' | 'sequenceQuiz';

export interface ArtifactSummary {
  id: string;
  title: string;
  createdAt: Date | Timestamp;
  type: ArtifactSummaryType;
  appliedRuleIds?: string[];
  // Generation lifecycle (missing means completed for backward compat)
  generationStatus?: GenerationStatus;
  generationError?: string;
}

export interface GetDirectoryContentsWithArtifactSummariesResponse extends GetDirectoryContentsResponse {
  artifactSummaries: ArtifactSummary[];
  resolvedRules: {
    rules: Rule[];
    inheritanceMap: { [directoryId: string]: Rule[] };
  };
}

export interface GetDirectoryAncestorsResponse {
  ancestors: Directory[];
}

export interface MoveDirectoryResponse {
  directory: Directory;
  affectedDescendants: number;
}

export interface DeleteDirectoryResponse {
  success: boolean;
  deletedDocumentCount: number;
  deletedDirectoryCount: number;
  deletedQuizCount: number;
  deletedFlashcardSetCount: number;
  deletedSlideDeckCount: number;
  deletedDiagramQuizCount?: number;
  deletedSequenceQuizCount?: number;
}

// Directory Validation Types
export interface DirectoryValidationResult {
  isValid: boolean;
  errors: string[];
}

// Directory Constants
export const DIRECTORY_CONSTRAINTS = {
  MAX_NAME_LENGTH: 100,
  MAX_DEPTH: 10,
  MAX_CHILDREN: 500,
  RESERVED_NAMES: ['root', 'system', 'admin'],
} as const;

// Document metadata for UI display
export interface DocumentMetadata {
  id: string;
  title: string;
  sourceType: 'url' | 'upload';
  sourceUrl?: string;
  fileName?: string;
  fileSize: number;
  wordCount: number;
  readingTime: number;
  createdAt: Date;
  quizCount?: number; // Number of quizzes created from this document
}

// API Types (Document-centric architecture)
export interface GenerateQuizRequest {
  documentIds: string[]; // One or more source documents to generate a quiz from
  directoryId?: string;
  quizName?: string; // Optional custom name, defaults to "Quiz from [Document Title]"
  additionalPrompt?: string; // Optional additional instructions for quiz generation
  ruleIds?: string[];
  /** @deprecated Auto-resolved from directory when omitted */
  quizRuleIds?: string[];
  /** @deprecated Auto-resolved from directory when omitted */
  followupRuleIds?: string[];
  additionalRuleIds?: string[];
  ruleResolutionMode?: RuleResolutionMode;
}

export interface GenerateQuizResponse {
  quizId: string;
  quiz: Quiz;
}

export interface GetQuizResponse {
  quiz: Quiz;
}

export interface GetUserQuizzesResponse {
  quizzes: Quiz[];
}

export interface GetDocumentQuizzesRequest {
  documentId: string;
}

export interface GetDocumentQuizzesResponse {
  quizzes: Quiz[];
}

// Enhanced Document API Types
export interface CreateDocumentRequest {
  title: string;
  description?: string;
  content: string;
  sourceType: DocumentSourceType;
  sourceUrl?: string;
  status?: DocumentStatus;
  tags?: string[];
  directoryId: string;
  ruleIds?: string[]; // Optional rule IDs for document generation
  ruleResolutionMode?: RuleResolutionMode;
}

export interface UpdateDocumentRequest {
  title?: string;
  description?: string;
  content?: string;
  status?: DocumentStatus;
  tags?: string[];
}

// Storage Types
export interface StorageFile {
  path: string;
  downloadUrl: string;
  metadata: StorageMetadata;
}

export interface StorageMetadata {
  contentType: string;
  size: number;
  timeCreated: string;
  updated: string;
  customMetadata: Record<string, string>;
}

// Enhanced Document Metadata
export interface DocumentMetadataEnhanced {
  title: string;
  sourceType: DocumentSourceType;
  wordCount: number;
  createdAt: Date;
  updatedAt: Date;
}

// Document API Types (New endpoints)
export interface CreateDocumentFromUrlRequest {
  url: string;
  title?: string; // Optional override for document title
  directoryId: string;
  ruleIds?: string[]; // Optional rules for content processing (Section 6)
  ruleResolutionMode?: RuleResolutionMode;
}

export interface CreateDocumentFromUrlsRequest {
  urls: string[];
  title?: string;
  directoryId: string;
  ruleIds?: string[];
  ruleResolutionMode?: RuleResolutionMode;
}

export type SupportedFileExtension =
  | 'pdf'
  | 'docx'
  | 'txt'
  | 'md'
  | 'csv'
  | 'pptx'
  | 'epub';

export interface FileExtractionResult {
  filename: string;
  originalType: string;
  markdownContent: string;
  wordCount: number;
  title: string | null;
  extension: SupportedFileExtension;
  originalSize: number;
  warnings?: string[];
  metadata?: {
    pageCount?: number;
    slideCount?: number;
    sheetCount?: number;
    chapterCount?: number;
  };
}

export interface UploadDocumentRequest {
  fileName: string;
  content: string; // Base64 encoded original file bytes
  mimeType?: string; // Browser-provided MIME type; advisory only
  size?: number; // Browser-reported original file size in bytes
  title?: string; // Optional override for document title
  directoryId: string;
  ruleIds?: string[]; // Optional rules for content processing (Section 6)
  ruleResolutionMode?: RuleResolutionMode;
}

// File Content Type for Text Prompt Context
export interface IFileContent {
  filename: string;
  content: string;
  size: number;
  type: string;
  source?: 'upload' | 'library'; // Optional: track source for logging
  documentId?: string; // Optional: document ID for library documents (ownership validation)
}

export interface GenerateFromPromptRequest {
  prompt: string; // User's text prompt (max 10000 characters)
  files?: IFileContent[]; // Optional reference documents (max 5 files)
  directoryId: string; // Directory to place the generated document
  ruleIds?: string[]; // Optional rules for content generation
  ruleResolutionMode?: RuleResolutionMode;
}

export interface GenerateFromPromptResponse extends StartGenerationResponse {
  documentId: string;
  title?: string;
  content?: string;
  wordCount?: number;
  metadata?: {
    originalPrompt: string;
    generatedAt: string;
    filesUsed?: number; // Number of context files used
  };
}

export interface GenerateFromScreenshotRequest {
  imageBase64: string;
  directoryId: string;
  title?: string;
  prompt?: string;
  ruleIds?: string[];
  ruleResolutionMode?: RuleResolutionMode;
}

export interface GenerateFromScreenshotResponse {
  documentId: string;
  title: string;
  content: string;
  wordCount: number;
  metadata: {
    generatedAt: string;
    sourceType: 'screenshot';
    directoryId: string;
    prompt?: string;
  };
}

export interface CreateDocumentResponse {
  documentId: string;
  document: Document;
}

export interface GetDocumentResponse {
  document: Document;
}

export interface GetUserDocumentsResponse {
  documents: DocumentMetadata[];
}

export interface DeleteDocumentRequest {
  documentId: string;
}

export interface DeleteDocumentResponse {
  success: boolean;
  deletedQuizCount?: number; // Number of associated quizzes deleted
}

// API Error Types
export interface ApiError {
  code: string;
  message: string;
}

export interface ApiResponse<T = unknown> {
  success: boolean;
  data?: T;
  error?: ApiError;
}

// Gemini Integration Types
export interface GeminiQuizQuestion {
  question: string;
  options: string[];
  correctAnswer: number;
  explanation?: string;
  hint?: string;
}

export interface GeminiQuizResponse {
  title: string;
  questions: GeminiQuizQuestion[];
}

// Web Scraping Types (Updated for markdown conversion)
export interface ScrapedContent {
  title: string;
  content: string; // Now represents clean, structured content
  markdownContent?: string; // Converted markdown content
  author?: string;
  publishDate?: string;
  wordCount: number;
}

// Firebase Storage Types
export interface StorageFile {
  path: string;
  downloadUrl: string;
  metadata: StorageMetadata;
}

// Content Processing Types
export interface ContentProcessor {
  processUrl(url: string): Promise<ProcessedContent>;
  processMarkdownFile(content: string, fileName: string): Promise<ProcessedContent>;
  validateContent(content: string): ContentValidationResult;
}

export interface ProcessedContent {
  title: string;
  content: string; // Clean markdown content
  wordCount: number;
  readingTime: number; // Calculated in minutes
  metadata: {
    sourceType: 'url' | 'upload';
    sourceUrl?: string;
    fileName?: string;
    originalSize: number;
    processedSize: number;
  };
}

export interface ContentValidationResult {
  isValid: boolean;
  errors: string[];
  warnings: string[];
  wordCount: number;
  estimatedReadingTime: number;
}

// File Upload Types
export interface FileUploadValidation {
  maxSize: number;
  allowedTypes: string[];
  allowedExtensions: string[];
}

export interface UploadValidationResult {
  isValid: boolean;
  errors: string[];
  fileInfo: {
    name: string;
    size: number;
    type: string;
    extension: string;
  };
}

// Quiz Followup API Types
export interface GenerateFollowupRequest {
  documentId: string;
  questionText: string;
  userSelectedAnswer: string;
  correctAnswer?: string;
  questionOptions?: string[];
  questionType?: 'multiple-choice' | 'diagram' | 'sequence';
  sequenceItems?: string[];
  userSequence?: string[];
  correctSequence?: string[];
  quizTitle?: string;
  followupRuleIds?: string[]; // Optional rule IDs for followup generation
}

export interface GenerateFollowupResponse {
  content: string;
}

export interface QuizFollowupContext {
  originalDocument: {
    title: string;
    content: string;
  };
  question: {
    text: string;
    options: string[];
    userAnswer: string;
    correctAnswer?: string;
    questionType?: 'multiple-choice' | 'diagram' | 'sequence';
    sequenceItems?: string[];
    userSequence?: string[];
    correctSequence?: string[];
  };
  quiz: {
    title: string;
  };
  customInstructions?: string; // Optional custom rules/instructions to inject
}

// Document Question API Types
export interface AskDocumentQuestionRequest {
  documentId: string;
  question: string;
  ruleIds?: string[];
}

export interface AskDocumentQuestionResponse {
  content: string;
}

export interface DocumentQuestionContext {
  document: {
    title: string;
    content: string;
  };
  question: string;
  customInstructions?: string;
}

// Directory Chat API Types
export type DirectoryChatRole = 'user' | 'assistant';

export interface DirectoryChatMessage {
  id: string;
  role: DirectoryChatRole;
  content: string;
  createdAt: string;
  seedKey?: string;
}

export interface DirectoryChatArtifactContext {
  type: 'quiz' | 'diagramQuiz' | 'sequenceQuiz' | 'slideDeck' | 'flashcardSet' | 'document';
  title?: string;
  question?: string;
  options?: string[];
  userAnswer?: string;
  correctAnswer?: string;
  explanation?: string;
  sequenceItems?: string[];
  userSequence?: string[];
  correctSequence?: string[];
  slideTitle?: string;
  slideContent?: string;
  speakerNotes?: string;
  followupRuleIds?: string[];
}

export interface RetrievedDirectoryChatChunk {
  documentId: string;
  documentTitle: string;
  text: string;
}

export interface DirectoryChatPromptContext {
  directoryName: string;
  userMessage: string;
  chatRules?: string;
  conversationSummary?: string;
  recentMessages: DirectoryChatMessage[];
  retrievedChunks: RetrievedDirectoryChatChunk[];
  artifactContext?: DirectoryChatArtifactContext;
}

export interface GetDirectoryChatRequest {
  directoryId: string;
}

export interface GetDirectoryChatResponse {
  directoryId: string;
  documentCount: number;
  messages: DirectoryChatMessage[];
  summary?: string;
}

export interface SendDirectoryChatMessageRequest {
  directoryId: string;
  message: string;
  seedKey?: string;
  artifactContext?: DirectoryChatArtifactContext;
}

export interface SendDirectoryChatMessageResponse {
  directoryId: string;
  documentCount: number;
  userMessage: DirectoryChatMessage;
  assistantMessage?: DirectoryChatMessage;
  messages: DirectoryChatMessage[];
  summary?: string;
}

// Auth Types
export interface User {
  uid: string;
  email: string;
  displayName?: string;
}

export interface AuthState {
  user: User | null;
  loading: boolean;
  error: string | null;
}

// Rules Feature Types
export enum RuleApplicability {
  SCRAPING = 'scraping',
  UPLOAD = 'upload',
  PROMPT = 'prompt',
  QUIZ = 'quiz',
  FOLLOWUP = 'followup',
  CHAT = 'chat',
  FLASHCARD = 'flashcard',
  FLASHCARD_DESC = 'flashcard_desc',
  SLIDE_DECK = 'slide_deck',
  DIAGRAM_QUIZ = 'diagram_quiz',
  SEQUENCE_QUIZ = 'sequence_quiz',
}

export enum RuleColor {
  RED = 'red',
  ORANGE = 'orange',
  YELLOW = 'yellow',
  GREEN = 'green',
  BLUE = 'blue',
  INDIGO = 'indigo',
  PURPLE = 'purple',
  PINK = 'pink',
  GRAY = 'gray',
}

export interface Rule {
  id: string;
  userId: string;
  name: string;
  description?: string;
  content: string; // Markdown content, max 100,000 chars
  color: RuleColor;
  tags: string[];
  applicableTo: RuleApplicability[];
  isDefault: boolean; // Auto-selected for operations
  directoryIds: string[]; // Directories this rule is attached to
  createdAt: Date | { toDate(): Date };
  updatedAt: Date | { toDate(): Date };
}

// Rule API Types
export interface CreateRuleRequest {
  name: string;
  description?: string;
  content: string;
  color: RuleColor;
  tags: string[];
  applicableTo: RuleApplicability[];
  isDefault?: boolean;
}

export interface UpdateRuleRequest {
  ruleId: string;
  name?: string;
  description?: string;
  content?: string;
  color?: RuleColor;
  tags?: string[];
  applicableTo?: RuleApplicability[];
  isDefault?: boolean;
}

export interface DeleteRuleRequest {
  ruleId: string;
}

export interface DeleteRuleResponse {
  success: boolean;
  error?: string; // Error message if rule is attached to directories
}

export interface AttachRuleToDirectoryRequest {
  ruleId: string;
  directoryId: string;
}

export interface DetachRuleFromDirectoryRequest {
  ruleId: string;
  directoryId: string;
}

export interface GetDirectoryRulesRequest {
  directoryId: string;
  includeAncestors?: boolean; // Defaults to true; set false for direct-only rules
}

export interface GetDirectoryRulesResponse {
  rules: Rule[];
  inheritanceMap: {
    [directoryId: string]: Rule[];
  };
}

export interface GetApplicableRulesRequest {
  directoryId: string;
  operation: RuleApplicability;
}

export interface GetApplicableRulesResponse {
  rules: Rule[];
}

export interface FormatRulesForPromptRequest {
  ruleIds: string[];
}

export interface FormatRulesForPromptResponse {
  formattedRules: string;
}

export interface GetRulesResponse {
  rules: Rule[];
}

export interface GetRuleResponse {
  rule: Rule;
}

export interface CreateRuleResponse {
  ruleId: string;
  rule: Rule;
}

export interface UpdateRuleResponse {
  rule: Rule;
}

export interface AttachRuleResponse {
  success: boolean;
}

export interface DetachRuleResponse {
  success: boolean;
}

// ─── Interaction Tracking Types ───────────────────────────────────────────────

export type ArtifactType =
  | 'document'
  | 'quiz'
  | 'flashcardSet'
  | 'slideDeck'
  | 'diagramQuiz'
  | 'sequenceQuiz';

export interface InteractionSession {
  id: string;
  userId: string;
  artifactId: string;
  artifactType: ArtifactType;
  directoryId: string;
  startedAt: Date | { toDate(): Date };
  lastActiveAt: Date | { toDate(): Date };
  activeSeconds: number;
  date: string; // "YYYY-MM-DD" partition key
}

export interface InteractionStat {
  id: string; // "{directoryId}_{date}"
  userId: string;
  directoryId: string;
  date: string; // "YYYY-MM-DD"
  totalSeconds: number;
  ownSeconds: number;
  byArtifactType: Record<ArtifactType, number>;
  sessionCount: number;
}

export interface FlushInteractionSessionRequest {
  artifactId: string;
  artifactType: ArtifactType;
  directoryId: string;
  activeSeconds: number;
  startedAt: string; // ISO string
}

export interface FlushInteractionSessionResponse {
  sessionId: string;
}

export interface GetInteractionStatsRequest {
  directoryId?: string; // omit for all directories
  startDate: string; // "YYYY-MM-DD"
  endDate: string; // "YYYY-MM-DD"
}

export interface GetInteractionStatsResponse {
  stats: InteractionStat[];
}

// ─── Learning Telemetry Types ───────────────────────────────────────────────

export type QuizTelemetryType = 'quiz' | 'diagramQuiz' | 'sequenceQuiz';

export type QuizAnswerValue = string | string[] | number | number[] | null;

export type LearningTelemetryEventType =
  | 'quiz_attempt_completed'
  | 'question_answered'
  | 'detailed_explanation_requested';

export interface RecordQuizAttemptAnswerInput {
  questionIndex: number;
  selectedAnswer: QuizAnswerValue;
  timeSpentMs?: number;
  detailedExplanationRequested?: boolean;
  detailedExplanationRequestedAt?: string;
}

export interface RecordQuizAttemptRequest {
  quizId: string;
  quizType: QuizTelemetryType;
  startedAt: string;
  completedAt: string;
  durationMs: number;
  answers: RecordQuizAttemptAnswerInput[];
}

export interface RecordQuizAttemptResponse {
  attemptId: string;
}

export interface RecordQuizExplanationRequest {
  quizId: string;
  quizType: QuizTelemetryType;
  questionIndex: number;
  requestedAt?: string;
}

export interface RecordQuizExplanationResponse {
  eventId: string;
}

export interface QuizAttemptAnswer {
  questionIndex: number;
  questionText: string;
  selectedAnswer: QuizAnswerValue;
  correctAnswer: QuizAnswerValue;
  isCorrect: boolean;
  timeSpentMs?: number;
  knowledge: QuestionKnowledgeMetadata;
  detailedExplanationRequested: boolean;
  detailedExplanationRequestedAt?: Date | { toDate(): Date };
}

export interface QuizAttempt {
  id: string;
  userId: string;
  quizId: string;
  quizType: QuizTelemetryType;
  documentIds: string[];
  directoryId: string;
  startedAt: Date | { toDate(): Date };
  completedAt: Date | { toDate(): Date };
  durationMs: number;
  score: number;
  totalQuestions: number;
  percentage: number;
  answers: QuizAttemptAnswer[];
  date: string;
}

export interface QuizStatsSummary {
  id: string;
  userId: string;
  quizId: string;
  quizType: QuizTelemetryType;
  directoryId: string;
  documentIds: string[];
  attemptCount: number;
  totalQuestions: number;
  totalScore: number;
  totalPercentage: number;
  totalDurationMs: number;
  bestScore: number;
  bestPercentage: number;
  latestScore: number;
  latestPercentage: number;
  incorrectAnswerCount: number;
  explanationRequestCount: number;
  lastAttemptAt?: Date | { toDate(): Date };
  updatedAt: Date | { toDate(): Date };
}

export interface QuestionStatsSummary {
  id: string;
  userId: string;
  quizId: string;
  quizType: QuizTelemetryType;
  questionIndex: number;
  questionText: string;
  knowledge: QuestionKnowledgeMetadata;
  answerCount: number;
  correctCount: number;
  incorrectCount: number;
  explanationRequestCount: number;
  updatedAt: Date | { toDate(): Date };
}

export interface KnowledgeStatsSummary {
  id: string;
  userId: string;
  date: string;
  subjectId?: string;
  subjectName?: string;
  knowledgeDomainId?: string;
  knowledgeDomainName?: string;
  topicTags: string[];
  answerCount: number;
  correctCount: number;
  incorrectCount: number;
  explanationRequestCount: number;
  updatedAt: Date | { toDate(): Date };
}

export interface LearningTelemetryEvent {
  id: string;
  userId: string;
  eventType: LearningTelemetryEventType;
  quizId: string;
  quizType: QuizTelemetryType;
  questionIndex?: number;
  isCorrect?: boolean;
  knowledge?: QuestionKnowledgeMetadata;
  occurredAt: Date | { toDate(): Date };
}

export interface GetQuizStatsRequest {
  quizId: string;
  quizType: QuizTelemetryType;
}

export interface GetQuizStatsResponse {
  stats: QuizStatsSummary | null;
}

// ─── Statistics Page Types ──────────────────────────────────────────────────

export type StatisticsTimeRangeKey = '7d' | '30d' | '90d' | 'all';

export type StatisticsQuizTypeFilter = QuizTelemetryType | 'all';

export interface StatisticsDateRangeRequest {
  startDate?: string; // "YYYY-MM-DD"; omitted for all time
  endDate?: string; // "YYYY-MM-DD"; omitted for all time
  quizType?: StatisticsQuizTypeFilter;
}

export interface StatisticsDocumentSummary {
  id: string;
  title: string;
}

export interface StatisticsOverviewMetrics {
  attemptCount: number;
  quizCount: number;
  answeredQuestionCount: number;
  correctAnswerCount: number;
  incorrectAnswerCount: number;
  explanationRequestCount: number;
  accuracyPercentage: number;
}

export interface StatisticsRecentFailure {
  id: string;
  attemptId: string;
  quizId: string;
  quizType: QuizTelemetryType;
  quizTitle?: string;
  questionIndex: number;
  questionText: string;
  selectedAnswer: QuizAnswerValue;
  selectedAnswerLabel: string;
  correctAnswer: QuizAnswerValue;
  correctAnswerLabel: string;
  knowledge: QuestionKnowledgeMetadata;
  sourceDocuments: StatisticsDocumentSummary[];
  occurredAt: string;
  repeatedFailureCount: number;
}

export interface StatisticsOverviewRecommendation {
  id: string;
  title: string;
  description: string;
  subjectKey: string;
  knowledgeDomainKey: string;
  subjectName: string;
  knowledgeDomainName: string;
  failureCount: number;
  explanationRequestCount: number;
  latestFailureAt?: string;
  sourceDocuments: StatisticsDocumentSummary[];
}

export interface GetStatisticsOverviewResponse {
  metrics: StatisticsOverviewMetrics;
  recentFailures: StatisticsRecentFailure[];
  recommendations: StatisticsOverviewRecommendation[];
}

export interface StatisticsQuizPerformanceItem {
  id: string;
  quizId: string;
  quizType: QuizTelemetryType;
  quizTitle?: string;
  sourceDocuments: StatisticsDocumentSummary[];
  attemptCount: number;
  answeredQuestionCount: number;
  correctAnswerCount: number;
  incorrectAnswerCount: number;
  explanationRequestCount: number;
  accuracyPercentage: number;
  bestPercentage: number;
  latestPercentage: number;
  totalDurationMs: number;
  lastAttemptAt?: string;
}

export interface GetStatisticsQuizPerformanceResponse {
  quizzes: StatisticsQuizPerformanceItem[];
  recentFailures: StatisticsRecentFailure[];
}

export interface StatisticsKnowledgeGapItem {
  id: string;
  subjectKey: string;
  subjectId?: string;
  subjectName: string;
  knowledgeDomainKey: string;
  knowledgeDomainId?: string;
  knowledgeDomainName: string;
  topicTags: string[];
  answerCount: number;
  correctCount: number;
  incorrectCount: number;
  explanationRequestCount: number;
  accuracyPercentage: number;
  recentFailureCount: number;
  latestFailureAt?: string;
  sourceDocuments: StatisticsDocumentSummary[];
}

export interface GetStatisticsKnowledgeGapsResponse {
  gaps: StatisticsKnowledgeGapItem[];
}

export interface StatisticsLearningTimeArtifact {
  id: string;
  artifactId: string;
  artifactType: ArtifactType;
  title: string;
  totalSeconds: number;
  sessionCount: number;
  lastActiveAt?: string;
}

export interface StatisticsLearningTimeByType {
  artifactType: ArtifactType;
  totalSeconds: number;
  sessionCount: number;
}

export interface GetStatisticsLearningTimeResponse {
  totalSeconds: number;
  sessionCount: number;
  byArtifactType: StatisticsLearningTimeByType[];
  topArtifacts: StatisticsLearningTimeArtifact[];
}

export interface StatisticsQuizDetailAttempt {
  attemptId: string;
  completedAt: string;
  score: number;
  totalQuestions: number;
  percentage: number;
  durationMs: number;
  incorrectAnswerCount: number;
}

export interface GetStatisticsQuizDetailRequest extends StatisticsDateRangeRequest {
  quizId: string;
  quizType: QuizTelemetryType;
}

export interface GetStatisticsQuizDetailResponse {
  quiz: StatisticsQuizPerformanceItem | null;
  attempts: StatisticsQuizDetailAttempt[];
  failedQuestions: StatisticsRecentFailure[];
}

export interface GetStatisticsKnowledgeDetailRequest extends StatisticsDateRangeRequest {
  subjectKey: string;
  knowledgeDomainKey: string;
}

export interface GetStatisticsKnowledgeDetailResponse {
  gap: StatisticsKnowledgeGapItem | null;
  failedQuestions: StatisticsRecentFailure[];
  relatedQuizzes: StatisticsQuizPerformanceItem[];
}